### ISSUE TITLE
glibc FORTIFY functions missing

### ISSUE THREAD

**Issue by evanrichter** [carstein/Annnotater#4]
I have this toy binary open in binja, and it has been compiled with FORTIFY enabled, meaning certain glibc function names have changed:

![current](https://user-images.githubusercontent.com/330292/52990202-02e8d080-33ff-11e9-9dff-a741f34689d2.png)

I manually added their definitions to create the expected results for this binary, but it should be completed and added upstream. How is `all_functions.json` generated? If it is just hand done, I can do it and add a pull request, but I suspect it might be easier on your end. Just let me know!

![expected](https://user-images.githubusercontent.com/330292/52990210-0da36580-33ff-11e9-9fc1-2698f1d6c664.png)

**Comment by carstein** [comment]
First of all, thank you for bringing this to my attention.
I personally never tested app compiled with FORTIFY and I don't know how names are generated so I'm not sure what would be the best course of actions.

If names are predictable maybe a small code change stripping __ and _chk would be enough and we can still use all_functions.json unchanged. I don't think there is much point adding multiple definitions for different names to this file (as it is already quite big).
Answering how this file is generated in the first place - well, I'm not very proud of it but I'm using lots of hackish scripts, some magic and function database from pwndbg. 

Let me do some tests and I will get back to you.
